### ISSUE TITLE
Flaky RenderTarget test

### ISSUE THREAD

**Issue by pmconne** [iTwin/itwinjs-core#4420]
**Describe the bug**
The following test failure in core-full-stack-tests occasionally occurs in CI jobs.
```
1) RenderTarget
       should override symbology:

      AssertionError: expected 4 to equal 2
      + expected - actual

      -4
      +2

      at D:/vsts_a/279/s/full-stack-tests/core/src/frontend/standalone/RenderTarget.test.ts:368:32
      at testOnScreenViewport (D:/vsts_a/279/s/full-stack-tests/core/src/frontend/TestViewport.ts:336:5)
      at testViewports (D:/vsts_a/279/s/full-stack-tests/core/src/frontend/TestViewport.ts:360:3)
      at testViewportsWithDpr (D:/vsts_a/279/s/full-stack-tests/core/src/frontend/TestViewport.ts:368:5)
      at Context.<anonymous> (D:/vsts_a/279/s/full-stack-tests/core/src/frontend/standalone/RenderTarget.test.ts:264:5)
```

**To Reproduce**
Submit PR. See if failure above occurs.

**Expected behavior**
Test should pass consistently.

**Desktop (please complete the applicable information):**

- iTwin.js Version [e.g. 2.5.3] master

**Additional context**
Most recent occurrence was in #4414. Seems to have begun occurring maybe 1-2 months prior?

**Comment by pmconne** [comment]
@markschlosseratbentley might this have coincided with your switching the tests to use `waitForSceneCompletion`?

**Comment by markschlosseratbentley** [comment]
> @markschlosseratbentley might this have coincided with your switching the tests to use `waitForSceneCompletion`?

@pmconne A specific test -- `WaitForSceneCompletion.test.ts` -- was added to exercise the `waitForSceneCompletion` API.  The rest of the tests all should still use whatever their pre-existing wait logic entailed.

**Comment by pmconne** [comment]
Seems to only occur on Windows.

**Comment by markschlosseratbentley** [comment]
This is not reproducible so far.
@markschlosseratbentley try on Windows.

**Comment by markschlosseratbentley** [comment]
Check if skipped.  Consider priority then.

**Comment by markschlosseratbentley** [comment]
Test is skipped; moving to Proposed so time can be spent looking at higher priority flaky tests.
