### ISSUE TITLE
Flaky test - Handle leak detected

### ISSUE THREAD

**Issue by grigasp** [iTwin/itwinjs-core#5017]
#### Build Info

- Repo: `itwinjs-core`
- Build Name: iTwin.js
- OS: Windows x64, Linux x64
- Test Suite Name: `core-i18n`, `core-markup`, `map-layers-formats`, `linear-referencing-backend`, `analytical-backend`

#### Error Detail

The specific cause is unclear - all tests succeed and error is thrown after the whole test suite is run.

```
==[ FAILURE: 2 operations ]====================================================

--[ FAILURE: @itwin/core-i18n ]-----------------------------[ 28.73 seconds ]--

WARNING: Tests attempted to load missing asset: "/locales/en-US/NotExist.json"
WARNING: Tests attempted to load missing asset: "/locales/en/NotExist.json"
WARNING: Tests attempted to load missing asset: "/locales/en-US/test1.json"
WARNING: Tests attempted to load missing asset: "/locales/en/test1.json"
WARNING: Tests attempted to load missing asset: "/locales/en-US/test2.json"
WARNING: Tests attempted to load missing asset: "/locales/en/test2.json"
WARNING: Tests attempted to load missing asset: "/locales/en-US/initial1.json"
WARNING: Tests attempted to load missing asset: "/locales/en/initial1.json"
WARNING: Tests attempted to load missing asset: "/locales/en-US/initial2.json"
WARNING: Tests attempted to load missing asset: "/locales/en/initial2.json"
##[error]Handle leak detected. Node was still running 5 seconds after tests completed.
Try running with the DEBUG_LEAKS env var set to see open handles.

Operations failed.

--[ FAILURE: @itwin/core-markup ]---------------------------[ 58.14 seconds ]--

##[error]Handle leak detected. Node was still running 5 seconds after tests completed.
Try running with the DEBUG_LEAKS env var set to see open handles.
```

#### Links to failing builds

-  **Jan 31, Windows:** https://dev.azure.com/bentleycs/iModelTechnologies/_build/results?buildId=1931113&view=logs&j=9f3a3068-7880-5994-433d-b92c1f9d379b&t=c78dc741-fe12-5d6a-c099-5134f70fdb0c

- **Feb 2, Linux:** https://bentleycs.visualstudio.com/iModelTechnologies/_build/results?buildId=1936502&view=logs&j=0aa84d8c-14fd-5636-fb46-99be2362d8e1&t=234e5986-45f5-5876-92cf-d939451fbda1&l=2332

- **Feb 2, Linux:** https://bentleycs.visualstudio.com/iModelTechnologies/_build/results?buildId=1936302&view=logs&j=0aa84d8c-14fd-5636-fb46-99be2362d8e1&t=234e5986-45f5-5876-92cf-d939451fbda1&l=2467

- **Feb 2, Linux:** https://bentleycs.visualstudio.com/iModelTechnologies/_build/results?buildId=1936060&view=logs&j=0aa84d8c-14fd-5636-fb46-99be2362d8e1&t=234e5986-45f5-5876-92cf-d939451fbda1&l=4756

#### Notes

Flaky, but have been occurring a lot over the past couple of weeks.

**Comment by grigasp** [comment]
There were 2 few more similar failures in different packages' test runs on Feb 2. Added to issue description.

**Comment by aruniverse** [comment]
https://github.com/iTwin/itwinjs-core/pull/5948#issuecomment-1709870966

**Comment by hl662** [comment]
@wgoehrig I'm investigating the handle leaks problem at present day, there's a pattern that all these errors pop up **after** a certa-run test suite is finished.  The difference between 2 years ago and now is that Node has a 30 sec timeout before it throws the handle leaks. This means there's a 30 sec buffer between a certa test suite, and another pkg's test suite being run.

We know that rush runs things in parallel, does not necessarily wait for one to finish before starting another, so I'm thinking this [example](https://dev.azure.com/bentleycs/iModelTechnologies/_build/results?buildId=3875358&view=logs&j=751a5ea6-e147-5a0b-b7c5-e28ecfcb00e2&t=742556c9-a44d-5542-8a03-cf20a9c5ac3e&l=8931), the handle leak was thrown during analytical-backend's test run, but the root cause might be either in core-markup, or presentation-fullstack-tests who both use certa. Those are the test suites run right before analytical-backend. Look at [this example too](https://dev.azure.com/bentleycs/iModelTechnologies/_build/results?buildId=3854304&view=logs&j=607f17b7-2b33-5225-6b64-00ff0e2e25e4&t=89ec18ca-7724-51ff-9cd4-fafaa006e1ca&l=9001), read the logs and notice how SIGTERM commands are emitted while the 'failed' test suites (linear-referencing, analytical, physical backend) are running (and passing).

 In the original description of this task, Node only had a 5 second timeout, that might be short enough that the handle leak problem is attributed to its actual culprit (core-i18n and/or core-markup who both use certa).

Is there a possibility that certa doesn't clean up open handles in time, perhaps Node's garbage collection takes longer than normal in rush cover, in CI where the agent might not be as performant, and resources are starved cause rush runs everything in parallel?

One more thing - I enabled DEBUG_LEAKS locally and ran rush cover. The first test suite run (any test suite, not just certa) was rpc-full-stack-tests. So no certa test suites ran before it, and my terminal didn't output any logs for a while, until eventually it did, emitting multiple test suite results at once. I was able to get the handle leak error, coming from rpc-full-stack-tests:

```
==[ rpc-full-stack-tests ]=======================================[ 13 of 58 ]==
WARNING: 1 test skipped in rpc-full-stack-tests
WARNING: 1 test skipped in rpc-full-stack-tests
ERROR: Handle leak detected. Node was still running 30 seconds after tests completed.
[WTF Node?] open handles:
- File descriptors: (note: stdio always exists)
  - fd 2 (stdio)
  - fd 1 (stdio)
- Child processes
  - PID 51870
Unable to determine callsite for "ChildProcess". Did you require `wtfnode` at the top of your entry point?
    - Entry point: unknown:0
    - STDIO file descriptors: 12, 14
  - PID 51910
Unable to determine callsite for "ChildProcess". Did you require `wtfnode` at the top of your entry point?
    - Entry point: unknown:0
    - STDIO file descriptors: 20, 22
- Servers:
  - :::5020 (HTTP)
    - Listeners:
Unable to determine callsite for "app". Did you require `wtfnode` at the top of your entry point?
      - request: app @ unknown:0
- Timers:
  - (30000 ~ 30 s) (anonymous) @ /Users/hoangnamle/Documents/itwinjs-core/common/temp/node_modules/.pnpm/playwright-core@1.47.1/node_modules/playwright-core/lib/server/browserType.js:218
- Others:
  - Pipe
[
  'PipeWrap',    'PipeWrap',
  'PipeWrap',    'PipeWrap',
  'ProcessWrap', 'PipeWrap',
  'PipeWrap',    'PipeWrap',
  'ProcessWrap', 'TCPServerWrap',
  'Timeout'
]
asyncId: 26469: type: Timeout, eid: 26250,triggerAsyncId: 26250, initStack: Error
    at AsyncHook.init (/Users/hoangnamle/Documents/itwinjs-core/tools/build/mocha-reporter/index.js:20:23)
    at emitInitNative (node:internal/async_hooks:202:43)
    at emitInitScript (node:internal/async_hooks:505:3)
    at initAsyncResource (node:internal/timers:170:5)
    at new Timeout (node:internal/timers:204:5)
    at setTimeout (node:timers:163:19)
    at setTimeout (/Users/hoangnamle/Documents/itwinjs-core/common/temp/node_modules/.pnpm/wtfnode@0.9.1/node_modules/wtfnode/index.js:286:37)
    at BentleyMochaReporter.epilogue (/Users/hoangnamle/Documents/itwinjs-core/tools/build/mocha-reporter/index.js:83:13)
    at Object.onceWrapper (node:events:638:28)
    at EventEmitter.emit (node:events:536:35)
asyncId: 26751: type: Timeout, eid: 26738,triggerAsyncId: 26738, initStack: Error
    at AsyncHook.init (/Users/hoangnamle/Documents/itwinjs-core/tools/build/mocha-reporter/index.js:20:23)
    at emitInitNative (node:internal/async_hooks:202:43)
    at emitInitScript (node:internal/async_hooks:505:3)
    at initAsyncResource (node:internal/timers:170:5)
    at new Timeout (node:internal/timers:204:5)
    at setTimeout (node:timers:163:19)
    at setTimeout (/Users/hoangnamle/Documents/itwinjs-core/common/temp/node_modules/.pnpm/wtfnode@0.9.1/node_modules/wtfnode/index.js:286:37)
    at /Users/hoangnamle/Documents/itwinjs-core/common/temp/node_modules/.pnpm/playwright-core@1.47.1/node_modules/playwright-core/lib/server/browserType.js:218:89
    at new Promise (<anonymous>)
    at closeOrKill (/Users/hoangnamle/Documents/itwinjs-core/common/temp/node_modules/.pnpm/playwright-core@1.47.1/node_modules/playwright-core/lib/server/browserType.js:218:48)
"rpc-full-stack-tests" completed with warnings in 1 minute 30.0 seconds.
```

**Comment by grigasp** [comment]
> presentation-fullstack-tests

they don't use certa

**Comment by pankhur94** [comment]
@grigasp would you mind having a look at this [branch](https://github.com/iTwin/itwinjs-core/tree/pankhur94/flaky-tests-debug-leaks). I've upgraded Playwright to v1.50.0, which now supports graceful shutdown.
I found that this issue was central to tests running unreliably on Certa. After investigating, I realized that the Playwright version we previously used (v1.47.1) did not handle shutdown gracefully, which likely contributed to the problems.

Additionally, I noticed that we were only closing the browser when tests were successful. In the case of test failures, the browser was not being closed, which could have left resources hanging and impacted subsequent tests.
I've updated the code to ensure that the browser is also closed when tests encounter errors.

I do see one of i18n tests failing. Need to figure out why that is happening.

**Comment by wgoehrig** [comment]
> there's a pattern that all these errors pop up **after** a certa-run test suite is finished

That is by design.  I [implemented this error](https://github.com/iTwin/itwinjs-core/blob/06313ff2dc8671959008c377d92437e3bbe2f57a/tools/build/src/mocha-reporter/index.ts#L91) because our test runner will hang if tests do not properly clean up after themselves (canceling timers, closing file handles, etc.)

IMO we should **not** be finding a workaround to force the test runner to exit before this error - it indicates there is a problem with one or more tests not properly isolating themselves in a way that could affect other tests and cause even more flakiness.

**Comment by tcobbs-bentley** [comment]
> > there's a pattern that all these errors pop up **after** a certa-run test suite is finished
> 
> That is by design. I [implemented this error](https://github.com/iTwin/itwinjs-core/blob/06313ff2dc8671959008c377d92437e3bbe2f57a/tools/build/src/mocha-reporter/index.ts#L91) because our test runner will hang if tests do not properly clean up after themselves (canceling timers, closing file handles, etc.)
> 
> IMO we should **not** be finding a workaround to force the test runner to exit before this error - it indicates there is a problem with one or more tests not properly isolating themselves in a way that could affect other tests and cause even more flakiness.

After debugging, I discovered that the `epilog` function where the handle leaks code exists is called before the tests think that they are done. (Specifically, before `_CertaReportResults` is called.) This appears to be the source of the problem, not tests that are broken. IMO, the handle leaks code should not execute until the tests at least _think_ that they are done. Right now, it seems like the flaky failures are due to the fact that using `epilog` to create the handle leaks timer is happens too soon.

I have a change that moves the handle leaks timeout after `_CertaReportResults`, but I'm not very happy with it, because it requires me to emit an event from `process`, and TypeScript has a specific list of events that it thinks that `process` should emit. It works fine with a typecast to any, but I'm not sure that it is something that is OK to do.

**Comment by tcobbs-bentley** [comment]
I pushed a [commit](https://github.com/iTwin/itwinjs-core/pull/8020/commits/491b477790d4755fc7cb9d8d8ea9cdaffabebcb7) with my changes that delay the handle leak detection code so that it does not execute until the tests have actually completed. I decreased the timeout to 10 seconds in that same commit, since it seems like that is now plenty.

**Comment by tcobbs-bentley** [comment]
@wgoehrig What do you think of Pankhur's [draft PR](https://github.com/iTwin/itwinjs-core/pull/8020)?

**Comment by wgoehrig** [comment]
Sorry for the delay in reviewing this.  I've approved #8020 because that seems like an appropriate workaround for now, but I do still think these failures are possibly a symptom of a real handle leak (which would now be masked by @tcobbs-bentley and @pankhur94's fix)...

**Comment by tcobbs-bentley** [comment]
It looks like the root cause of the remaining handle leaks is containers be left open by tests. These need to be tracked down and fixed, but there is a hopeful workaround to use in the meantime (calling `unref` on the container's token refresh timer).

**Comment by tcobbs-bentley** [comment]
@wgoehrig: I tracked down a container being left open by tests. The cloud container opened in RealityDataAccess.test.ts never gets disconnected. I don't understand why, though. The imodel that it is associated with is properly closed.

For reference, the iTwin for this test is named `iModelJsIntegrationTest`, and the iModel is named `Tuxford_qa`.

I debugged with a breakpoint in `IModelDb.close`, and that breakpoint is hit and seems to execute correctly. Looking for likely spots that would be expected to disconnect the cloud container, I found `CloudSqlite.DbAccess.close`. I put a breakpoint there, but that breakpoint was never hit.

**Comment by tcobbs-bentley** [comment]
@khanaffan @wgoehrig: The fact that the cloud container does not get disconnected when the imodel that opened it is closed seems like a bug. Do either of you have any thoughts on this? Is it a bug? Is it intended behavior? If it's a bug, what do you think the proper way is to disconnect it?

**Comment by anmolshres98** [comment]
I agree with @tcobbs-bentley 's assessment here. a ViewStore container is scoped to a distinct iModel, so it's a bug that it wasn't closed when the associated iModel closed. #9539 closes it in IModelDb.close(). checkpoint containers are host-scoped (cached and reused across attaches), so those are now disconnected in IModelHost.shutdown() instead.

@khanaffan @wgoehrig lmk if I'm missing something here or in the #9539 thread 🤔

I also removed the .unref() mask Travis had added to keep the leak detector quiet, since that hides real leaks and shouldn't be the permanent fix for this imo

**Comment by anmolshres98** [comment]
seeing no counterarguments, I am publishing my draft PR
