### ISSUE TITLE
Clarification regarding one issue

### ISSUE THREAD

**Issue by abhijan1234** [iTwin/itwinjs-core#5100]
Facing this issue while running an application on VM. Please check the below log for this issue.

(node:10700) UnhandledPromiseRejectionWarning: Error: The specified module could not be found.
\\?\C:\Users\Admin\Desktop\Backup\DesktopBridgeOrchestrators\common\temp\node_modules\@bentley\imodeljs-native\imodeljs-win32-x64\imodeljs.node
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1800)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1199:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:1800)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at Module.patchedRequire [as require] (C:\Users\Admin\Desktop\Backup\DesktopBridgeOrchestrators\common\temp\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Function.load (C:\Users\Admin\Desktop\Backup\DesktopBridgeOrchestrators\common\temp\node_modules\@bentley\imodeljs-native\NativeLibrary.js:65:31)
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:10700) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Comment by aruniverse** [comment]
Can you provide some more information?
What version of iTwin.js are you using? 
Are you webpacking your connector? If so, what does your webpack config look like?
