### ISSUE TITLE
Flakey core-full-stack-tests

### ISSUE THREAD

**Issue by aruniverse** [iTwin/itwinjs-core#5417]
--[ FAILURE: core-full-stack-tests ]------------------------[ 32.88 seconds ]--

WARNING: Tests attempted to load missing asset: "/locales/en-US/CoreTools.json"
WARNING: Tests attempted to load missing asset: "/locales/en/iModelJs.json"
WARNING: Tests attempted to load missing asset: "/locales/en-US/iModelJs.json"
WARNING: Tests attempted to load missing asset: "/locales/en/CoreTools.json"
WARNING: Tests attempted to load missing asset: "/images/imodeljs-icon.svg"
WARNING: Tests attempted to load missing asset: "/locales/en-US/Editor.json"
WARNING: Tests attempted to load missing asset: "/locales/en/Editor.json"
TypeError: Cannot read properties of undefined (reading 'purgeTileTrees')
    at IModelTileRpcImpl.purgeTileTrees (D:\vsts_a\4\s\core\backend\src\rpc-impl\IModelTileRpcImpl.ts:201:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at RpcSessionInvocation.resolve (D:\vsts_a\4\s\core\common\src\rpc\core\RpcInvocation.ts:168:14)
    at RpcHandler.request (D:\vsts_a\4\s\core\backend\src\LocalhostIpcHost.ts:68:25)
    at D:\vsts_a\4\s\core\backend\src\IpcHost.ts:161:26
    at IpcWebSocketBackend.processMessages (D:\vsts_a\4\s\core\common\src\ipc\IpcWebSocket.ts:175:26)
    at IpcWebSocketBackend.dispatch (D:\vsts_a\4\s\core\common\src\ipc\IpcWebSocket.ts:159:5)

              I suspect it actually might be #5400 , looks like it dropped some changes made in #4067 which was to resolve #4044

5400:
![image](https://user-images.githubusercontent.com/11051042/232877320-6854970b-39ac-415c-857e-d3bcfc6a7a14.png)

4067:
![image](https://user-images.githubusercontent.com/11051042/232877383-e959f59e-2f20-4bc5-b394-3c6bb340d15a.png)

@swbsi

_Originally posted by @aruniverse in https://github.com/iTwin/itwinjs-core/issues/5407#issuecomment-1513651751_

**Comment by aruniverse** [comment]
<img width="801" alt="image" src="https://user-images.githubusercontent.com/11051042/233094986-b96b8b95-930f-410c-94f5-a7e9f99ef1c2.png">
