### ISSUE TITLE
`backend-webpack-tools` displays a warning when `@itwin/service-authorization` is referenced

### ISSUE THREAD

**Issue by MindaugasButkus** [iTwin/itwinjs-core#5738]
**Describe the bug**
`backend-webpack-tools build -s ./lib/main.js -o ./dist` throws this error when `@itwin/service-authorization` is referenced:
```
{
    "message": "Can't copy external package \"node:url\" - it is not installed.\nTo fix this, either npm install node:url or wrap the import in a try/catch.",
    "stack": "Error: Can't copy external package \"node:url\" - it is not installed.\nTo fix this, either npm install node:url or wrap the import in a try/catch.\n    at CopyExternalsPlugin.handleModule (D:\\dev\\ts-sandbox\\node_modules\\@itwin\\core-webpack-tools\\lib\\plugins\\CopyExternalsPlugin.js:47:39)\n    at D:\\dev\\ts-sandbox\\node_modules\\@itwin\\core-webpack-tools\\lib\\plugins\\CopyExternalsPlugin.js:26:46\n    at Hook.eval [as call] (eval at create (D:\\dev\\ts-sandbox\\node_modules\\tapable\\lib\\HookCodeFactory.js:19:10), <anonymous>:7:1)\n    at D:\\dev\\ts-sandbox\\node_modules\\webpack\\lib\\Compilation.js:1375:28\n    at ExternalModule.needBuild (D:\\dev\\ts-sandbox\\node_modules\\webpack\\lib\\ExternalModule.js:451:10)\n    at Compilation._buildModule (D:\\dev\\ts-sandbox\\node_modules\\webpack\\lib\\Compilation.js:1358:10)\n    at D:\\dev\\ts-sandbox\\node_modules\\webpack\\lib\\util\\AsyncQueue.js:305:10\n    at Hook.eval [as callAsync] (eval at create (D:\\dev\\ts-sandbox\\node_modules\\tapable\\lib\\HookCodeFactory.js:33:10), <anonymous>:6:1)\n    at AsyncQueue._startProcessing (D:\\dev\\ts-sandbox\\node_modules\\webpack\\lib\\util\\AsyncQueue.js:295:26)\n    at AsyncQueue._ensureProcessing (D:\\dev\\ts-sandbox\\node_modules\\webpack\\lib\\util\\AsyncQueue.js:282:12)"
  }
```

**To Reproduce**

1. `npm i @itwin/service-authorization@^1.0.0`
2. In main.ts:
```
import { ServiceAuthorizationClient } from "@itwin/service-authorization";

const client = new ServiceAuthorizationClient({
    clientId: "lala",
    clientSecret: "no-secrets",
    scope: "",
});
```
3. `tsc 1>&2 && backend-webpack-tools build -s ./lib/main.js -o ./dist` (compile main.ts into main.js, then run webpack)
4. See warning

**Expected behavior**
I do not expect to see this warning if the built product is meant to be used in an environment where node libs will be present.

**Desktop (please complete the applicable information):**

- OS: Microsoft Windows Version 22H2 (OS Build 22624.1992)
- Browser - not used
- Node version 18.16.0
- iTwin.js Version 4.0.4

**Additional context**
Line where node:url is referenced in the auth client: https://github.com/iTwin/auth-clients/blob/main/packages/service/src/OIDCDiscoveryClient.ts#L5C2-L5C32

**Comment by aruniverse** [comment]
Thx for reporting this. Should be a relatively easy fix

Offending line: https://github.com/iTwin/itwinjs-core/blob/master/tools/webpack-core/src/plugins/CopyExternalsPlugin.ts#L40

[builtinModules](https://nodejs.org/api/module.html#modulebuiltinmodules)
<img width="504" alt="image" src="https://github.com/iTwin/itwinjs-core/assets/11051042/a570705e-25d0-488b-8c25-9a2a4e381547">

looks like the plugin doesnt properly support [node protocol imports](https://2ality.com/2021/12/node-protocol-imports.html)
