### ISSUE TITLE
`SchemaContext` throws when simultaneously requesting same schema

### ISSUE THREAD

**Issue by grigasp** [iTwin/itwinjs-core#6542]
**Describe the bug**

When simultaneously requesting same schema many times, `SchemaContext` throws an error, saying it's already loaded. In addition, it's being unnecessarily loaded more than once.

**To Reproduce**

Minimal code to reproduce (I believe you can use any iModel for this):

```ts
const schemas = new SchemaContext();
const locater = new SchemaJsonLocater((schemaName) => iModel.getSchemaProps(schemaName));
schemas.addLocater(locater);
await Promise.all(
  [...Array(100).keys()].map(async () => {
    return schemas.getSchema(new SchemaKey("BisCore"));
  }),
);
```

The above snippet, when executed, throws:
```
Error (35055): The schema, BisCore.01.00.08, already exists within this cache.
    at SchemaCache.addSchemaSync (D:\dev\gh\presentation\node_modules\.pnpm\@itwin+ecschema-metadata@4.4.0_@itwin+core-bentley@4.4.0_@itwin+core-quantity@4.4.0\node_modules\@itwin\ecschema-metadata\src\Context.ts:152:13)
    at SchemaContext.addSchemaSync (D:\dev\gh\presentation\node_modules\.pnpm\@itwin+ecschema-metadata@4.4.0_@itwin+core-bentley@4.4.0_@itwin+core-quantity@4.4.0\node_modules\@itwin\ecschema-metadata\src\Context.ts:278:24)
    at SchemaReadHelper.readSchemaSync (D:\dev\gh\presentation\node_modules\.pnpm\@itwin+ecschema-metadata@4.4.0_@itwin+core-bentley@4.4.0_@itwin+core-quantity@4.4.0\node_modules\@itwin\ecschema-metadata\src\Deserialization\Helper.ts:157:19)
    at Function.fromJsonSync (D:\dev\gh\presentation\node_modules\.pnpm\@itwin+ecschema-metadata@4.4.0_@itwin+core-bentley@4.4.0_@itwin+core-quantity@4.4.0\node_modules\@itwin\ecschema-metadata\src\Metadata\Schema.ts:638:21)
    at SchemaJsonLocater.getSchemaSync (D:\dev\gh\presentation\node_modules\.pnpm\@itwin+ecschema-metadata@4.4.0_@itwin+core-bentley@4.4.0_@itwin+core-quantity@4.4.0\node_modules\@itwin\ecschema-metadata\src\SchemaJsonLocater.ts:59:19)
    at SchemaJsonLocater.getSchema (D:\dev\gh\presentation\node_modules\.pnpm\@itwin+ecschema-metadata@4.4.0_@itwin+core-bentley@4.4.0_@itwin+core-quantity@4.4.0\node_modules\@itwin\ecschema-metadata\src\SchemaJsonLocater.ts:35:17)
    at SchemaContext.getSchema (D:\dev\gh\presentation\node_modules\.pnpm\@itwin+ecschema-metadata@4.4.0_@itwin+core-bentley@4.4.0_@itwin+core-quantity@4.4.0\node_modules\@itwin\ecschema-metadata\src\Context.ts:322:36) {
  errorNumber: 35055,
  _metaData: undefined
}
```

**Expected behavior**

The requested schema is loaded once an all requests resolve to the same schema without any errors.

**Desktop:**

- iTwin.js Version: 4.4.0

**Comment by grigasp** [comment]
I had a workaround for this problem:
```ts
  const schemaCache = new Map<string, Promise<EC.Schema | undefined>>();
  return {
    async getSchema(name) {
      // workaround for https://github.com/iTwin/itwinjs-core/issues/6542
      let schema = schemaCache.get(name);
      // istanbul ignore else
      if (!schema) {
        schema = schemaContext.getSchema(new CoreSchemaKey(name)).then((coreSchema) => (coreSchema ? createECSchema(coreSchema) : undefined));
        schema.catch(() => schemaCache.delete(name));
        schemaCache.set(name, schema);
      }
      return schema;
    },
  };
```

However, I just came up with a more complicated case:
1. `getSchema` is called with `SchemaX`, which references `SchemaY`.
2. Before the promise is resolved, `getSchema` is called with `SchemaY`. However, while `SchemaX` is being resolved, it also caches the referenced `SchemaY` schema, and then when we get to resolving `SchemaY` - the same "The schema, SchemaY.01.00.00, already exists within this cache" error is thrown.

@ColinKerr, could your team prioritize this?
